### ISSUE TITLE
Slurm output files not saved in run_dir

### ISSUE THREAD

**Issue by awlishar** [DIGIfusion/enchanted-surrogates#15]
The SLURM .out/.err files are saved in the directory from where the run is initiated. I would prefer that each output file is saved within the corresponding run's directory. 

The HELENA runner changes into the run_dir in 'single_code_run'. The directory would need to be changed before 'single_code_run' is called. I would have liked to do it in 'run_simulation_task', changing into run_dir right after it is created. @fusionby2030 This didn't work well with TGLF, right? Any ideas?

**Comment by fusionby2030** [comment]
I'm curious if this change was ever added or upstreamed.  If so could you point to the commit or branch and then we can close the issue? :--)
